name: skillforge
type: web

routes:
  - name: default
    port: 80  # Use 3000 if it's a Node.js app

build:
  - name: docker-build
    command: docker build -t my-koyeb-app .

run:
  - name: docker-run
    command: docker run -p 80:80 my-koyeb-app
